print('Welcome to a Mad Libs Game')
print('A Shinigami [verb] my [adjective] [noun1] out of the [noun2] as if he were a vegetarian fishing a [noun3] out of his salad.')
verb = input('Please input a verb for the sentence: ')
adj = input('Please input an adjective for the sentence: ')
n1 = input('Please input a noun for noun1 in the sentence: ')
n2 = input('Please input a noun for noun2 in the sentence: ')
n3 = input('Please input a noun for noun3 in the sentence: ')
print('Here is your Mad Libs')
print('A Shinigami',verb+' my',adj,n1+' out of the',n2+' as if he were a vegetarian fishing a',n3+' out of his salad.')