print('Student Report Card 2020')
student1 = input('Input Score for Andy: ')
student2 = input('Input Score for Marry: ')
student3 = input('Input Score for John: ')
studentscore = float(student1), float(student2), float(student3)
average = sum(studentscore) / 3
print('Student Scores List')
print('Andy   :',student1)
print('Marry  :',student2)
print('John   :',student3)
print('Average Student Score :',average)